version = 0.1
[default.deploy.parameters]
stack_name = "callback-pattern"
resolve_s3 = true
s3_prefix = "callback-pattern"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
